defaults:
  - _self_
  - acquisition: random
  - task: burgers
  - hydra: base
  - prob_model: base
  - sel_model: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

wandb:
  group: test
  name: null
  project: al4pde

seed: 23
num_epochs: 500
num_epochs_sel: 30
start_al_iter: 0 # for restarting
num_al_iter: 5

restore_checkpoint: false
checkpoint_file_name: "latest.pt" # cannot load intermediate models right now (would have to delete later data)
checkpoint_id: "c1papzmi"
